#pragma once
#include <stddef.h>
#include "lib.hpp"

/* __WIN32__ */
#if !defined(__WIN32__) && (defined(_WIN32) || defined(WIN32) || defined(__CYGWIN__))
#  define __WIN32__
#endif

/* GLAPI, part 1 (use WINGDIAPI, if defined) */
#if defined(__WIN32__) && defined(WINGDIAPI)
#  define GLAPI WINGDIAPI
#endif

/* GLAPI, part 2 */
#if !defined(GLAPI)
#  if defined(_MSC_VER)
#    define GLAPI __declspec(dllimport)
#  elif defined(__LCC__) && defined(__WIN32__)
#    define GLAPI __stdcall
#  else
#    define GLAPI extern
#  endif
#endif

/* APIENTRY */
#if !defined(APIENTRY)
#  if defined(__WIN32__)
#    define APIENTRY __stdcall
#  else
#    define APIENTRY
#  endif
#endif

namespace axl {
namespace glw {
namespace gl {

// GL_VERSION_1_1
typedef unsigned int GLenum;
typedef unsigned int GLbitfield;
typedef unsigned int GLuint;
typedef int GLint;
typedef GLint* GLintptr;
typedef int GLsizei;
typedef GLsizei* GLsizeiptr;
typedef unsigned char GLboolean;
typedef signed char GLbyte;
typedef short GLshort;
typedef unsigned char GLubyte;
typedef unsigned short GLushort;
typedef unsigned long GLulong;
typedef float GLfloat;
typedef float GLclampf;
typedef double GLdouble;
typedef double GLclampd;
typedef void GLvoid;
#if defined(_MSC_VER) && _MSC_VER < 1400
typedef __int64 GLint64EXT;
typedef unsigned __int64 GLuint64EXT;
#elif defined(_MSC_VER) || defined(__BORLANDC__)
typedef signed long long GLint64EXT;
typedef unsigned long long GLuint64EXT;
#else
#  if defined(__MINGW32__) || defined(__CYGWIN__)
#include <inttypes.h>
#  endif
typedef int64_t GLint64EXT;
typedef uint64_t GLuint64EXT;
#endif
typedef GLint64EXT  GLint64;
typedef GLuint64EXT GLuint64;
typedef struct __GLsync *GLsync;

constexpr long GL_ZERO = 0;
constexpr long GL_FALSE = 0;
constexpr long GL_LOGIC_OP = 0x0BF1;
constexpr long GL_NONE = 0;
constexpr long GL_TEXTURE_COMPONENTS = 0x1003;
constexpr long GL_NO_ERROR = 0;
constexpr long GL_POINTS = 0x0000;
constexpr long GL_CURRENT_BIT = 0x00000001;
constexpr long GL_TRUE = 1;
constexpr long GL_ONE = 1;
constexpr long GL_CLIENT_PIXEL_STORE_BIT = 0x00000001;
constexpr long GL_LINES = 0x0001;
constexpr long GL_LINE_LOOP = 0x0002;
constexpr long GL_POINT_BIT = 0x00000002;
constexpr long GL_CLIENT_VERTEX_ARRAY_BIT = 0x00000002;
constexpr long GL_LINE_STRIP = 0x0003;
constexpr long GL_LINE_BIT = 0x00000004;
constexpr long GL_TRIANGLES = 0x0004;
constexpr long GL_TRIANGLE_STRIP = 0x0005;
constexpr long GL_TRIANGLE_FAN = 0x0006;
constexpr long GL_QUADS = 0x0007;
constexpr long GL_QUAD_STRIP = 0x0008;
constexpr long GL_POLYGON_BIT = 0x00000008;
constexpr long GL_POLYGON = 0x0009;
constexpr long GL_POLYGON_STIPPLE_BIT = 0x00000010;
constexpr long GL_PIXEL_MODE_BIT = 0x00000020;
constexpr long GL_LIGHTING_BIT = 0x00000040;
constexpr long GL_FOG_BIT = 0x00000080;
constexpr long GL_DEPTH_BUFFER_BIT = 0x00000100;
constexpr long GL_ACCUM = 0x0100;
constexpr long GL_LOAD = 0x0101;
constexpr long GL_RETURN = 0x0102;
constexpr long GL_MULT = 0x0103;
constexpr long GL_ADD = 0x0104;
constexpr long GL_NEVER = 0x0200;
constexpr long GL_ACCUM_BUFFER_BIT = 0x00000200;
constexpr long GL_LESS = 0x0201;
constexpr long GL_EQUAL = 0x0202;
constexpr long GL_LEQUAL = 0x0203;
constexpr long GL_GREATER = 0x0204;
constexpr long GL_NOTEQUAL = 0x0205;
constexpr long GL_GEQUAL = 0x0206;
constexpr long GL_ALWAYS = 0x0207;
constexpr long GL_SRC_COLOR = 0x0300;
constexpr long GL_ONE_MINUS_SRC_COLOR = 0x0301;
constexpr long GL_SRC_ALPHA = 0x0302;
constexpr long GL_ONE_MINUS_SRC_ALPHA = 0x0303;
constexpr long GL_DST_ALPHA = 0x0304;
constexpr long GL_ONE_MINUS_DST_ALPHA = 0x0305;
constexpr long GL_DST_COLOR = 0x0306;
constexpr long GL_ONE_MINUS_DST_COLOR = 0x0307;
constexpr long GL_SRC_ALPHA_SATURATE = 0x0308;
constexpr long GL_STENCIL_BUFFER_BIT = 0x00000400;
constexpr long GL_FRONT_LEFT = 0x0400;
constexpr long GL_FRONT_RIGHT = 0x0401;
constexpr long GL_BACK_LEFT = 0x0402;
constexpr long GL_BACK_RIGHT = 0x0403;
constexpr long GL_FRONT = 0x0404;
constexpr long GL_BACK = 0x0405;
constexpr long GL_LEFT = 0x0406;
constexpr long GL_RIGHT = 0x0407;
constexpr long GL_FRONT_AND_BACK = 0x0408;
constexpr long GL_AUX0 = 0x0409;
constexpr long GL_AUX1 = 0x040A;
constexpr long GL_AUX2 = 0x040B;
constexpr long GL_AUX3 = 0x040C;
constexpr long GL_INVALID_ENUM = 0x0500;
constexpr long GL_INVALID_VALUE = 0x0501;
constexpr long GL_INVALID_OPERATION = 0x0502;
constexpr long GL_STACK_OVERFLOW = 0x0503;
constexpr long GL_STACK_UNDERFLOW = 0x0504;
constexpr long GL_OUT_OF_MEMORY = 0x0505;
constexpr long GL_2D = 0x0600;
constexpr long GL_3D = 0x0601;
constexpr long GL_3D_COLOR = 0x0602;
constexpr long GL_3D_COLOR_TEXTURE = 0x0603;
constexpr long GL_4D_COLOR_TEXTURE = 0x0604;
constexpr long GL_PASS_THROUGH_TOKEN = 0x0700;
constexpr long GL_POINT_TOKEN = 0x0701;
constexpr long GL_LINE_TOKEN = 0x0702;
constexpr long GL_POLYGON_TOKEN = 0x0703;
constexpr long GL_BITMAP_TOKEN = 0x0704;
constexpr long GL_DRAW_PIXEL_TOKEN = 0x0705;
constexpr long GL_COPY_PIXEL_TOKEN = 0x0706;
constexpr long GL_LINE_RESET_TOKEN = 0x0707;
constexpr long GL_EXP = 0x0800;
constexpr long GL_VIEWPORT_BIT = 0x00000800;
constexpr long GL_EXP2 = 0x0801;
constexpr long GL_CW = 0x0900;
constexpr long GL_CCW = 0x0901;
constexpr long GL_COEFF = 0x0A00;
constexpr long GL_ORDER = 0x0A01;
constexpr long GL_DOMAIN = 0x0A02;
constexpr long GL_CURRENT_COLOR = 0x0B00;
constexpr long GL_CURRENT_INDEX = 0x0B01;
constexpr long GL_CURRENT_NORMAL = 0x0B02;
constexpr long GL_CURRENT_TEXTURE_COORDS = 0x0B03;
constexpr long GL_CURRENT_RASTER_COLOR = 0x0B04;
constexpr long GL_CURRENT_RASTER_INDEX = 0x0B05;
constexpr long GL_CURRENT_RASTER_TEXTURE_COORDS = 0x0B06;
constexpr long GL_CURRENT_RASTER_POSITION = 0x0B07;
constexpr long GL_CURRENT_RASTER_POSITION_VALID = 0x0B08;
constexpr long GL_CURRENT_RASTER_DISTANCE = 0x0B09;
constexpr long GL_POINT_SMOOTH = 0x0B10;
constexpr long GL_POINT_SIZE = 0x0B11;
constexpr long GL_POINT_SIZE_RANGE = 0x0B12;
constexpr long GL_POINT_SIZE_GRANULARITY = 0x0B13;
constexpr long GL_LINE_SMOOTH = 0x0B20;
constexpr long GL_LINE_WIDTH = 0x0B21;
constexpr long GL_LINE_WIDTH_RANGE = 0x0B22;
constexpr long GL_LINE_WIDTH_GRANULARITY = 0x0B23;
constexpr long GL_LINE_STIPPLE = 0x0B24;
constexpr long GL_LINE_STIPPLE_PATTERN = 0x0B25;
constexpr long GL_LINE_STIPPLE_REPEAT = 0x0B26;
constexpr long GL_LIST_MODE = 0x0B30;
constexpr long GL_MAX_LIST_NESTING = 0x0B31;
constexpr long GL_LIST_BASE = 0x0B32;
constexpr long GL_LIST_INDEX = 0x0B33;
constexpr long GL_POLYGON_MODE = 0x0B40;
constexpr long GL_POLYGON_SMOOTH = 0x0B41;
constexpr long GL_POLYGON_STIPPLE = 0x0B42;
constexpr long GL_EDGE_FLAG = 0x0B43;
constexpr long GL_CULL_FACE = 0x0B44;
constexpr long GL_CULL_FACE_MODE = 0x0B45;
constexpr long GL_FRONT_FACE = 0x0B46;
constexpr long GL_LIGHTING = 0x0B50;
constexpr long GL_LIGHT_MODEL_LOCAL_VIEWER = 0x0B51;
constexpr long GL_LIGHT_MODEL_TWO_SIDE = 0x0B52;
constexpr long GL_LIGHT_MODEL_AMBIENT = 0x0B53;
constexpr long GL_SHADE_MODEL = 0x0B54;
constexpr long GL_COLOR_MATERIAL_FACE = 0x0B55;
constexpr long GL_COLOR_MATERIAL_PARAMETER = 0x0B56;
constexpr long GL_COLOR_MATERIAL = 0x0B57;
constexpr long GL_FOG = 0x0B60;
constexpr long GL_FOG_INDEX = 0x0B61;
constexpr long GL_FOG_DENSITY = 0x0B62;
constexpr long GL_FOG_START = 0x0B63;
constexpr long GL_FOG_END = 0x0B64;
constexpr long GL_FOG_MODE = 0x0B65;
constexpr long GL_FOG_COLOR = 0x0B66;
constexpr long GL_DEPTH_RANGE = 0x0B70;
constexpr long GL_DEPTH_TEST = 0x0B71;
constexpr long GL_DEPTH_WRITEMASK = 0x0B72;
constexpr long GL_DEPTH_CLEAR_VALUE = 0x0B73;
constexpr long GL_DEPTH_FUNC = 0x0B74;
constexpr long GL_ACCUM_CLEAR_VALUE = 0x0B80;
constexpr long GL_STENCIL_TEST = 0x0B90;
constexpr long GL_STENCIL_CLEAR_VALUE = 0x0B91;
constexpr long GL_STENCIL_FUNC = 0x0B92;
constexpr long GL_STENCIL_VALUE_MASK = 0x0B93;
constexpr long GL_STENCIL_FAIL = 0x0B94;
constexpr long GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95;
constexpr long GL_STENCIL_PASS_DEPTH_PASS = 0x0B96;
constexpr long GL_STENCIL_REF = 0x0B97;
constexpr long GL_STENCIL_WRITEMASK = 0x0B98;
constexpr long GL_MATRIX_MODE = 0x0BA0;
constexpr long GL_NORMALIZE = 0x0BA1;
constexpr long GL_VIEWPORT = 0x0BA2;
constexpr long GL_MODELVIEW_STACK_DEPTH = 0x0BA3;
constexpr long GL_PROJECTION_STACK_DEPTH = 0x0BA4;
constexpr long GL_TEXTURE_STACK_DEPTH = 0x0BA5;
constexpr long GL_MODELVIEW_MATRIX = 0x0BA6;
constexpr long GL_PROJECTION_MATRIX = 0x0BA7;
constexpr long GL_TEXTURE_MATRIX = 0x0BA8;
constexpr long GL_ATTRIB_STACK_DEPTH = 0x0BB0;
constexpr long GL_CLIENT_ATTRIB_STACK_DEPTH = 0x0BB1;
constexpr long GL_ALPHA_TEST = 0x0BC0;
constexpr long GL_ALPHA_TEST_FUNC = 0x0BC1;
constexpr long GL_ALPHA_TEST_REF = 0x0BC2;
constexpr long GL_DITHER = 0x0BD0;
constexpr long GL_BLEND_DST = 0x0BE0;
constexpr long GL_BLEND_SRC = 0x0BE1;
constexpr long GL_BLEND = 0x0BE2;
constexpr long GL_LOGIC_OP_MODE = 0x0BF0;
constexpr long GL_INDEX_LOGIC_OP = 0x0BF1;
constexpr long GL_COLOR_LOGIC_OP = 0x0BF2;
constexpr long GL_AUX_BUFFERS = 0x0C00;
constexpr long GL_DRAW_BUFFER = 0x0C01;
constexpr long GL_READ_BUFFER = 0x0C02;
constexpr long GL_SCISSOR_BOX = 0x0C10;
constexpr long GL_SCISSOR_TEST = 0x0C11;
constexpr long GL_INDEX_CLEAR_VALUE = 0x0C20;
constexpr long GL_INDEX_WRITEMASK = 0x0C21;
constexpr long GL_COLOR_CLEAR_VALUE = 0x0C22;
constexpr long GL_COLOR_WRITEMASK = 0x0C23;
constexpr long GL_INDEX_MODE = 0x0C30;
constexpr long GL_RGBA_MODE = 0x0C31;
constexpr long GL_DOUBLEBUFFER = 0x0C32;
constexpr long GL_STEREO = 0x0C33;
constexpr long GL_RENDER_MODE = 0x0C40;
constexpr long GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50;
constexpr long GL_POINT_SMOOTH_HINT = 0x0C51;
constexpr long GL_LINE_SMOOTH_HINT = 0x0C52;
constexpr long GL_POLYGON_SMOOTH_HINT = 0x0C53;
constexpr long GL_FOG_HINT = 0x0C54;
constexpr long GL_TEXTURE_GEN_S = 0x0C60;
constexpr long GL_TEXTURE_GEN_T = 0x0C61;
constexpr long GL_TEXTURE_GEN_R = 0x0C62;
constexpr long GL_TEXTURE_GEN_Q = 0x0C63;
constexpr long GL_PIXEL_MAP_I_TO_I = 0x0C70;
constexpr long GL_PIXEL_MAP_S_TO_S = 0x0C71;
constexpr long GL_PIXEL_MAP_I_TO_R = 0x0C72;
constexpr long GL_PIXEL_MAP_I_TO_G = 0x0C73;
constexpr long GL_PIXEL_MAP_I_TO_B = 0x0C74;
constexpr long GL_PIXEL_MAP_I_TO_A = 0x0C75;
constexpr long GL_PIXEL_MAP_R_TO_R = 0x0C76;
constexpr long GL_PIXEL_MAP_G_TO_G = 0x0C77;
constexpr long GL_PIXEL_MAP_B_TO_B = 0x0C78;
constexpr long GL_PIXEL_MAP_A_TO_A = 0x0C79;
constexpr long GL_PIXEL_MAP_I_TO_I_SIZE = 0x0CB0;
constexpr long GL_PIXEL_MAP_S_TO_S_SIZE = 0x0CB1;
constexpr long GL_PIXEL_MAP_I_TO_R_SIZE = 0x0CB2;
constexpr long GL_PIXEL_MAP_I_TO_G_SIZE = 0x0CB3;
constexpr long GL_PIXEL_MAP_I_TO_B_SIZE = 0x0CB4;
constexpr long GL_PIXEL_MAP_I_TO_A_SIZE = 0x0CB5;
constexpr long GL_PIXEL_MAP_R_TO_R_SIZE = 0x0CB6;
constexpr long GL_PIXEL_MAP_G_TO_G_SIZE = 0x0CB7;
constexpr long GL_PIXEL_MAP_B_TO_B_SIZE = 0x0CB8;
constexpr long GL_PIXEL_MAP_A_TO_A_SIZE = 0x0CB9;
constexpr long GL_UNPACK_SWAP_BYTES = 0x0CF0;
constexpr long GL_UNPACK_LSB_FIRST = 0x0CF1;
constexpr long GL_UNPACK_ROW_LENGTH = 0x0CF2;
constexpr long GL_UNPACK_SKIP_ROWS = 0x0CF3;
constexpr long GL_UNPACK_SKIP_PIXELS = 0x0CF4;
constexpr long GL_UNPACK_ALIGNMENT = 0x0CF5;
constexpr long GL_PACK_SWAP_BYTES = 0x0D00;
constexpr long GL_PACK_LSB_FIRST = 0x0D01;
constexpr long GL_PACK_ROW_LENGTH = 0x0D02;
constexpr long GL_PACK_SKIP_ROWS = 0x0D03;
constexpr long GL_PACK_SKIP_PIXELS = 0x0D04;
constexpr long GL_PACK_ALIGNMENT = 0x0D05;
constexpr long GL_MAP_COLOR = 0x0D10;
constexpr long GL_MAP_STENCIL = 0x0D11;
constexpr long GL_INDEX_SHIFT = 0x0D12;
constexpr long GL_INDEX_OFFSET = 0x0D13;
constexpr long GL_RED_SCALE = 0x0D14;
constexpr long GL_RED_BIAS = 0x0D15;
constexpr long GL_ZOOM_X = 0x0D16;
constexpr long GL_ZOOM_Y = 0x0D17;
constexpr long GL_GREEN_SCALE = 0x0D18;
constexpr long GL_GREEN_BIAS = 0x0D19;
constexpr long GL_BLUE_SCALE = 0x0D1A;
constexpr long GL_BLUE_BIAS = 0x0D1B;
constexpr long GL_ALPHA_SCALE = 0x0D1C;
constexpr long GL_ALPHA_BIAS = 0x0D1D;
constexpr long GL_DEPTH_SCALE = 0x0D1E;
constexpr long GL_DEPTH_BIAS = 0x0D1F;
constexpr long GL_MAX_EVAL_ORDER = 0x0D30;
constexpr long GL_MAX_LIGHTS = 0x0D31;
constexpr long GL_MAX_CLIP_PLANES = 0x0D32;
constexpr long GL_MAX_TEXTURE_SIZE = 0x0D33;
constexpr long GL_MAX_PIXEL_MAP_TABLE = 0x0D34;
constexpr long GL_MAX_ATTRIB_STACK_DEPTH = 0x0D35;
constexpr long GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36;
constexpr long GL_MAX_NAME_STACK_DEPTH = 0x0D37;
constexpr long GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38;
constexpr long GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39;
constexpr long GL_MAX_VIEWPORT_DIMS = 0x0D3A;
constexpr long GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = 0x0D3B;
constexpr long GL_SUBPIXEL_BITS = 0x0D50;
constexpr long GL_INDEX_BITS = 0x0D51;
constexpr long GL_RED_BITS = 0x0D52;
constexpr long GL_GREEN_BITS = 0x0D53;
constexpr long GL_BLUE_BITS = 0x0D54;
constexpr long GL_ALPHA_BITS = 0x0D55;
constexpr long GL_DEPTH_BITS = 0x0D56;
constexpr long GL_STENCIL_BITS = 0x0D57;
constexpr long GL_ACCUM_RED_BITS = 0x0D58;
constexpr long GL_ACCUM_GREEN_BITS = 0x0D59;
constexpr long GL_ACCUM_BLUE_BITS = 0x0D5A;
constexpr long GL_ACCUM_ALPHA_BITS = 0x0D5B;
constexpr long GL_NAME_STACK_DEPTH = 0x0D70;
constexpr long GL_AUTO_NORMAL = 0x0D80;
constexpr long GL_MAP1_COLOR_4 = 0x0D90;
constexpr long GL_MAP1_INDEX = 0x0D91;
constexpr long GL_MAP1_NORMAL = 0x0D92;
constexpr long GL_MAP1_TEXTURE_COORD_1 = 0x0D93;
constexpr long GL_MAP1_TEXTURE_COORD_2 = 0x0D94;
constexpr long GL_MAP1_TEXTURE_COORD_3 = 0x0D95;
constexpr long GL_MAP1_TEXTURE_COORD_4 = 0x0D96;
constexpr long GL_MAP1_VERTEX_3 = 0x0D97;
constexpr long GL_MAP1_VERTEX_4 = 0x0D98;
constexpr long GL_MAP2_COLOR_4 = 0x0DB0;
constexpr long GL_MAP2_INDEX = 0x0DB1;
constexpr long GL_MAP2_NORMAL = 0x0DB2;
constexpr long GL_MAP2_TEXTURE_COORD_1 = 0x0DB3;
constexpr long GL_MAP2_TEXTURE_COORD_2 = 0x0DB4;
constexpr long GL_MAP2_TEXTURE_COORD_3 = 0x0DB5;
constexpr long GL_MAP2_TEXTURE_COORD_4 = 0x0DB6;
constexpr long GL_MAP2_VERTEX_3 = 0x0DB7;
constexpr long GL_MAP2_VERTEX_4 = 0x0DB8;
constexpr long GL_MAP1_GRID_DOMAIN = 0x0DD0;
constexpr long GL_MAP1_GRID_SEGMENTS = 0x0DD1;
constexpr long GL_MAP2_GRID_DOMAIN = 0x0DD2;
constexpr long GL_MAP2_GRID_SEGMENTS = 0x0DD3;
constexpr long GL_TEXTURE_1D = 0x0DE0;
constexpr long GL_TEXTURE_2D = 0x0DE1;
constexpr long GL_FEEDBACK_BUFFER_POINTER = 0x0DF0;
constexpr long GL_FEEDBACK_BUFFER_SIZE = 0x0DF1;
constexpr long GL_FEEDBACK_BUFFER_TYPE = 0x0DF2;
constexpr long GL_SELECTION_BUFFER_POINTER = 0x0DF3;
constexpr long GL_SELECTION_BUFFER_SIZE = 0x0DF4;
constexpr long GL_TEXTURE_WIDTH = 0x1000;
constexpr long GL_TRANSFORM_BIT = 0x00001000;
constexpr long GL_TEXTURE_HEIGHT = 0x1001;
constexpr long GL_TEXTURE_INTERNAL_FORMAT = 0x1003;
constexpr long GL_TEXTURE_BORDER_COLOR = 0x1004;
constexpr long GL_TEXTURE_BORDER = 0x1005;
constexpr long GL_DONT_CARE = 0x1100;
constexpr long GL_FASTEST = 0x1101;
constexpr long GL_NICEST = 0x1102;
constexpr long GL_AMBIENT = 0x1200;
constexpr long GL_DIFFUSE = 0x1201;
constexpr long GL_SPECULAR = 0x1202;
constexpr long GL_POSITION = 0x1203;
constexpr long GL_SPOT_DIRECTION = 0x1204;
constexpr long GL_SPOT_EXPONENT = 0x1205;
constexpr long GL_SPOT_CUTOFF = 0x1206;
constexpr long GL_CONSTANT_ATTENUATION = 0x1207;
constexpr long GL_LINEAR_ATTENUATION = 0x1208;
constexpr long GL_QUADRATIC_ATTENUATION = 0x1209;
constexpr long GL_COMPILE = 0x1300;
constexpr long GL_COMPILE_AND_EXECUTE = 0x1301;
constexpr long GL_BYTE = 0x1400;
constexpr long GL_UNSIGNED_BYTE = 0x1401;
constexpr long GL_SHORT = 0x1402;
constexpr long GL_UNSIGNED_SHORT = 0x1403;
constexpr long GL_INT = 0x1404;
constexpr long GL_UNSIGNED_INT = 0x1405;
constexpr long GL_FLOAT = 0x1406;
constexpr long GL_2_BYTES = 0x1407;
constexpr long GL_3_BYTES = 0x1408;
constexpr long GL_4_BYTES = 0x1409;
constexpr long GL_DOUBLE = 0x140A;
constexpr long GL_CLEAR = 0x1500;
constexpr long GL_AND = 0x1501;
constexpr long GL_AND_REVERSE = 0x1502;
constexpr long GL_COPY = 0x1503;
constexpr long GL_AND_INVERTED = 0x1504;
constexpr long GL_NOOP = 0x1505;
constexpr long GL_XOR = 0x1506;
constexpr long GL_OR = 0x1507;
constexpr long GL_NOR = 0x1508;
constexpr long GL_EQUIV = 0x1509;
constexpr long GL_INVERT = 0x150A;
constexpr long GL_OR_REVERSE = 0x150B;
constexpr long GL_COPY_INVERTED = 0x150C;
constexpr long GL_OR_INVERTED = 0x150D;
constexpr long GL_NAND = 0x150E;
constexpr long GL_SET = 0x150F;
constexpr long GL_EMISSION = 0x1600;
constexpr long GL_SHININESS = 0x1601;
constexpr long GL_AMBIENT_AND_DIFFUSE = 0x1602;
constexpr long GL_COLOR_INDEXES = 0x1603;
constexpr long GL_MODELVIEW = 0x1700;
constexpr long GL_PROJECTION = 0x1701;
constexpr long GL_TEXTURE = 0x1702;
constexpr long GL_COLOR = 0x1800;
constexpr long GL_DEPTH = 0x1801;
constexpr long GL_STENCIL = 0x1802;
constexpr long GL_COLOR_INDEX = 0x1900;
constexpr long GL_STENCIL_INDEX = 0x1901;
constexpr long GL_DEPTH_COMPONENT = 0x1902;
constexpr long GL_RED = 0x1903;
constexpr long GL_GREEN = 0x1904;
constexpr long GL_BLUE = 0x1905;
constexpr long GL_ALPHA = 0x1906;
constexpr long GL_RGB = 0x1907;
constexpr long GL_RGBA = 0x1908;
constexpr long GL_LUMINANCE = 0x1909;
constexpr long GL_LUMINANCE_ALPHA = 0x190A;
constexpr long GL_BITMAP = 0x1A00;
constexpr long GL_POINT = 0x1B00;
constexpr long GL_LINE = 0x1B01;
constexpr long GL_FILL = 0x1B02;
constexpr long GL_RENDER = 0x1C00;
constexpr long GL_FEEDBACK = 0x1C01;
constexpr long GL_SELECT = 0x1C02;
constexpr long GL_FLAT = 0x1D00;
constexpr long GL_SMOOTH = 0x1D01;
constexpr long GL_KEEP = 0x1E00;
constexpr long GL_REPLACE = 0x1E01;
constexpr long GL_INCR = 0x1E02;
constexpr long GL_DECR = 0x1E03;
constexpr long GL_VENDOR = 0x1F00;
constexpr long GL_RENDERER = 0x1F01;
constexpr long GL_VERSION = 0x1F02;
constexpr long GL_EXTENSIONS = 0x1F03;
constexpr long GL_S = 0x2000;
constexpr long GL_ENABLE_BIT = 0x00002000;
constexpr long GL_T = 0x2001;
constexpr long GL_R = 0x2002;
constexpr long GL_Q = 0x2003;
constexpr long GL_MODULATE = 0x2100;
constexpr long GL_DECAL = 0x2101;
constexpr long GL_TEXTURE_ENV_MODE = 0x2200;
constexpr long GL_TEXTURE_ENV_COLOR = 0x2201;
constexpr long GL_TEXTURE_ENV = 0x2300;
constexpr long GL_EYE_LINEAR = 0x2400;
constexpr long GL_OBJECT_LINEAR = 0x2401;
constexpr long GL_SPHERE_MAP = 0x2402;
constexpr long GL_TEXTURE_GEN_MODE = 0x2500;
constexpr long GL_OBJECT_PLANE = 0x2501;
constexpr long GL_EYE_PLANE = 0x2502;
constexpr long GL_NEAREST = 0x2600;
constexpr long GL_LINEAR = 0x2601;
constexpr long GL_NEAREST_MIPMAP_NEAREST = 0x2700;
constexpr long GL_LINEAR_MIPMAP_NEAREST = 0x2701;
constexpr long GL_NEAREST_MIPMAP_LINEAR = 0x2702;
constexpr long GL_LINEAR_MIPMAP_LINEAR = 0x2703;
constexpr long GL_TEXTURE_MAG_FILTER = 0x2800;
constexpr long GL_TEXTURE_MIN_FILTER = 0x2801;
constexpr long GL_TEXTURE_WRAP_S = 0x2802;
constexpr long GL_TEXTURE_WRAP_T = 0x2803;
constexpr long GL_CLAMP = 0x2900;
constexpr long GL_REPEAT = 0x2901;
constexpr long GL_POLYGON_OFFSET_UNITS = 0x2A00;
constexpr long GL_POLYGON_OFFSET_POINT = 0x2A01;
constexpr long GL_POLYGON_OFFSET_LINE = 0x2A02;
constexpr long GL_R3_G3_B2 = 0x2A10;
constexpr long GL_V2F = 0x2A20;
constexpr long GL_V3F = 0x2A21;
constexpr long GL_C4UB_V2F = 0x2A22;
constexpr long GL_C4UB_V3F = 0x2A23;
constexpr long GL_C3F_V3F = 0x2A24;
constexpr long GL_N3F_V3F = 0x2A25;
constexpr long GL_C4F_N3F_V3F = 0x2A26;
constexpr long GL_T2F_V3F = 0x2A27;
constexpr long GL_T4F_V4F = 0x2A28;
constexpr long GL_T2F_C4UB_V3F = 0x2A29;
constexpr long GL_T2F_C3F_V3F = 0x2A2A;
constexpr long GL_T2F_N3F_V3F = 0x2A2B;
constexpr long GL_T2F_C4F_N3F_V3F = 0x2A2C;
constexpr long GL_T4F_C4F_N3F_V4F = 0x2A2D;
constexpr long GL_CLIP_PLANE0 = 0x3000;
constexpr long GL_CLIP_PLANE1 = 0x3001;
constexpr long GL_CLIP_PLANE2 = 0x3002;
constexpr long GL_CLIP_PLANE3 = 0x3003;
constexpr long GL_CLIP_PLANE4 = 0x3004;
constexpr long GL_CLIP_PLANE5 = 0x3005;
constexpr long GL_LIGHT0 = 0x4000;
constexpr long GL_COLOR_BUFFER_BIT = 0x00004000;
constexpr long GL_LIGHT1 = 0x4001;
constexpr long GL_LIGHT2 = 0x4002;
constexpr long GL_LIGHT3 = 0x4003;
constexpr long GL_LIGHT4 = 0x4004;
constexpr long GL_LIGHT5 = 0x4005;
constexpr long GL_LIGHT6 = 0x4006;
constexpr long GL_LIGHT7 = 0x4007;
constexpr long GL_HINT_BIT = 0x00008000;
constexpr long GL_POLYGON_OFFSET_FILL = 0x8037;
constexpr long GL_POLYGON_OFFSET_FACTOR = 0x8038;
constexpr long GL_ALPHA4 = 0x803B;
constexpr long GL_ALPHA8 = 0x803C;
constexpr long GL_ALPHA12 = 0x803D;
constexpr long GL_ALPHA16 = 0x803E;
constexpr long GL_LUMINANCE4 = 0x803F;
constexpr long GL_LUMINANCE8 = 0x8040;
constexpr long GL_LUMINANCE12 = 0x8041;
constexpr long GL_LUMINANCE16 = 0x8042;
constexpr long GL_LUMINANCE4_ALPHA4 = 0x8043;
constexpr long GL_LUMINANCE6_ALPHA2 = 0x8044;
constexpr long GL_LUMINANCE8_ALPHA8 = 0x8045;
constexpr long GL_LUMINANCE12_ALPHA4 = 0x8046;
constexpr long GL_LUMINANCE12_ALPHA12 = 0x8047;
constexpr long GL_LUMINANCE16_ALPHA16 = 0x8048;
constexpr long GL_INTENSITY = 0x8049;
constexpr long GL_INTENSITY4 = 0x804A;
constexpr long GL_INTENSITY8 = 0x804B;
constexpr long GL_INTENSITY12 = 0x804C;
constexpr long GL_INTENSITY16 = 0x804D;
constexpr long GL_RGB4 = 0x804F;
constexpr long GL_RGB5 = 0x8050;
constexpr long GL_RGB8 = 0x8051;
constexpr long GL_RGB10 = 0x8052;
constexpr long GL_RGB12 = 0x8053;
constexpr long GL_RGB16 = 0x8054;
constexpr long GL_RGBA2 = 0x8055;
constexpr long GL_RGBA4 = 0x8056;
constexpr long GL_RGB5_A1 = 0x8057;
constexpr long GL_RGBA8 = 0x8058;
constexpr long GL_RGB10_A2 = 0x8059;
constexpr long GL_RGBA12 = 0x805A;
constexpr long GL_RGBA16 = 0x805B;
constexpr long GL_TEXTURE_RED_SIZE = 0x805C;
constexpr long GL_TEXTURE_GREEN_SIZE = 0x805D;
constexpr long GL_TEXTURE_BLUE_SIZE = 0x805E;
constexpr long GL_TEXTURE_ALPHA_SIZE = 0x805F;
constexpr long GL_TEXTURE_LUMINANCE_SIZE = 0x8060;
constexpr long GL_TEXTURE_INTENSITY_SIZE = 0x8061;
constexpr long GL_PROXY_TEXTURE_1D = 0x8063;
constexpr long GL_PROXY_TEXTURE_2D = 0x8064;
constexpr long GL_TEXTURE_PRIORITY = 0x8066;
constexpr long GL_TEXTURE_RESIDENT = 0x8067;
constexpr long GL_TEXTURE_BINDING_1D = 0x8068;
constexpr long GL_TEXTURE_BINDING_2D = 0x8069;
constexpr long GL_VERTEX_ARRAY = 0x8074;
constexpr long GL_NORMAL_ARRAY = 0x8075;
constexpr long GL_COLOR_ARRAY = 0x8076;
constexpr long GL_INDEX_ARRAY = 0x8077;
constexpr long GL_TEXTURE_COORD_ARRAY = 0x8078;
constexpr long GL_EDGE_FLAG_ARRAY = 0x8079;
constexpr long GL_VERTEX_ARRAY_SIZE = 0x807A;
constexpr long GL_VERTEX_ARRAY_TYPE = 0x807B;
constexpr long GL_VERTEX_ARRAY_STRIDE = 0x807C;
constexpr long GL_NORMAL_ARRAY_TYPE = 0x807E;
constexpr long GL_NORMAL_ARRAY_STRIDE = 0x807F;
constexpr long GL_COLOR_ARRAY_SIZE = 0x8081;
constexpr long GL_COLOR_ARRAY_TYPE = 0x8082;
constexpr long GL_COLOR_ARRAY_STRIDE = 0x8083;
constexpr long GL_INDEX_ARRAY_TYPE = 0x8085;
constexpr long GL_INDEX_ARRAY_STRIDE = 0x8086;
constexpr long GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088;
constexpr long GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089;
constexpr long GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A;
constexpr long GL_EDGE_FLAG_ARRAY_STRIDE = 0x808C;
constexpr long GL_VERTEX_ARRAY_POINTER = 0x808E;
constexpr long GL_NORMAL_ARRAY_POINTER = 0x808F;
constexpr long GL_COLOR_ARRAY_POINTER = 0x8090;
constexpr long GL_INDEX_ARRAY_POINTER = 0x8091;
constexpr long GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092;
constexpr long GL_EDGE_FLAG_ARRAY_POINTER = 0x8093;
constexpr long GL_COLOR_INDEX1_EXT = 0x80E2;
constexpr long GL_COLOR_INDEX2_EXT = 0x80E3;
constexpr long GL_COLOR_INDEX4_EXT = 0x80E4;
constexpr long GL_COLOR_INDEX8_EXT = 0x80E5;
constexpr long GL_COLOR_INDEX12_EXT = 0x80E6;
constexpr long GL_COLOR_INDEX16_EXT = 0x80E7;
constexpr long GL_EVAL_BIT = 0x00010000;
constexpr long GL_LIST_BIT = 0x00020000;
constexpr long GL_TEXTURE_BIT = 0x00040000;
constexpr long GL_SCISSOR_BIT = 0x00080000;
constexpr long GL_ALL_ATTRIB_BITS = 0x000fffff;
constexpr long GL_CLIENT_ALL_ATTRIB_BITS = 0xffffffff;
extern "C" {
GLAPI void APIENTRY glAccum (GLenum op, GLfloat value);
GLAPI void APIENTRY glAlphaFunc (GLenum func, GLclampf ref);
GLAPI GLboolean APIENTRY glAreTexturesResident (GLsizei n, const GLuint *textures, GLboolean *residences);
GLAPI void APIENTRY glArrayElement (GLint i);
GLAPI void APIENTRY glBegin (GLenum mode);
GLAPI void APIENTRY glBindTexture (GLenum target, GLuint texture);
GLAPI void APIENTRY glBitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
GLAPI void APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor);
GLAPI void APIENTRY glCallList (GLuint list);
GLAPI void APIENTRY glCallLists (GLsizei n, GLenum type, const void *lists);
GLAPI void APIENTRY glClear (GLbitfield mask);
GLAPI void APIENTRY glClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
GLAPI void APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
GLAPI void APIENTRY glClearDepth (GLclampd depth);
GLAPI void APIENTRY glClearIndex (GLfloat c);
GLAPI void APIENTRY glClearStencil (GLint s);
GLAPI void APIENTRY glClipPlane (GLenum plane, const GLdouble *equation);
GLAPI void APIENTRY glColor3b (GLbyte red, GLbyte green, GLbyte blue);
GLAPI void APIENTRY glColor3bv (const GLbyte *v);
GLAPI void APIENTRY glColor3d (GLdouble red, GLdouble green, GLdouble blue);
GLAPI void APIENTRY glColor3dv (const GLdouble *v);
GLAPI void APIENTRY glColor3f (GLfloat red, GLfloat green, GLfloat blue);
GLAPI void APIENTRY glColor3fv (const GLfloat *v);
GLAPI void APIENTRY glColor3i (GLint red, GLint green, GLint blue);
GLAPI void APIENTRY glColor3iv (const GLint *v);
GLAPI void APIENTRY glColor3s (GLshort red, GLshort green, GLshort blue);
GLAPI void APIENTRY glColor3sv (const GLshort *v);
GLAPI void APIENTRY glColor3ub (GLubyte red, GLubyte green, GLubyte blue);
GLAPI void APIENTRY glColor3ubv (const GLubyte *v);
GLAPI void APIENTRY glColor3ui (GLuint red, GLuint green, GLuint blue);
GLAPI void APIENTRY glColor3uiv (const GLuint *v);
GLAPI void APIENTRY glColor3us (GLushort red, GLushort green, GLushort blue);
GLAPI void APIENTRY glColor3usv (const GLushort *v);
GLAPI void APIENTRY glColor4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
GLAPI void APIENTRY glColor4bv (const GLbyte *v);
GLAPI void APIENTRY glColor4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
GLAPI void APIENTRY glColor4dv (const GLdouble *v);
GLAPI void APIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
GLAPI void APIENTRY glColor4fv (const GLfloat *v);
GLAPI void APIENTRY glColor4i (GLint red, GLint green, GLint blue, GLint alpha);
GLAPI void APIENTRY glColor4iv (const GLint *v);
GLAPI void APIENTRY glColor4s (GLshort red, GLshort green, GLshort blue, GLshort alpha);
GLAPI void APIENTRY glColor4sv (const GLshort *v);
GLAPI void APIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
GLAPI void APIENTRY glColor4ubv (const GLubyte *v);
GLAPI void APIENTRY glColor4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha);
GLAPI void APIENTRY glColor4uiv (const GLuint *v);
GLAPI void APIENTRY glColor4us (GLushort red, GLushort green, GLushort blue, GLushort alpha);
GLAPI void APIENTRY glColor4usv (const GLushort *v);
GLAPI void APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
GLAPI void APIENTRY glColorMaterial (GLenum face, GLenum mode);
GLAPI void APIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const void *pointer);
GLAPI void APIENTRY glCopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
GLAPI void APIENTRY glCopyTexImage1D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
GLAPI void APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
GLAPI void APIENTRY glCopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
GLAPI void APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
GLAPI void APIENTRY glCullFace (GLenum mode);
GLAPI void APIENTRY glDeleteLists (GLuint list, GLsizei range);
GLAPI void APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures);
GLAPI void APIENTRY glDepthFunc (GLenum func);
GLAPI void APIENTRY glDepthMask (GLboolean flag);
GLAPI void APIENTRY glDepthRange (GLclampd zNear, GLclampd zFar);
GLAPI void APIENTRY glDisable (GLenum cap);
GLAPI void APIENTRY glDisableClientState (GLenum array);
GLAPI void APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count);
GLAPI void APIENTRY glDrawBuffer (GLenum mode);
GLAPI void APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const void *indices);
GLAPI void APIENTRY glDrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
GLAPI void APIENTRY glEdgeFlag (GLboolean flag);
GLAPI void APIENTRY glEdgeFlagPointer (GLsizei stride, const void *pointer);
GLAPI void APIENTRY glEdgeFlagv (const GLboolean *flag);
GLAPI void APIENTRY glEnable (GLenum cap);
GLAPI void APIENTRY glEnableClientState (GLenum array);
GLAPI void APIENTRY glEnd (void);
GLAPI void APIENTRY glEndList (void);
GLAPI void APIENTRY glEvalCoord1d (GLdouble u);
GLAPI void APIENTRY glEvalCoord1dv (const GLdouble *u);
GLAPI void APIENTRY glEvalCoord1f (GLfloat u);
GLAPI void APIENTRY glEvalCoord1fv (const GLfloat *u);
GLAPI void APIENTRY glEvalCoord2d (GLdouble u, GLdouble v);
GLAPI void APIENTRY glEvalCoord2dv (const GLdouble *u);
GLAPI void APIENTRY glEvalCoord2f (GLfloat u, GLfloat v);
GLAPI void APIENTRY glEvalCoord2fv (const GLfloat *u);
GLAPI void APIENTRY glEvalMesh1 (GLenum mode, GLint i1, GLint i2);
GLAPI void APIENTRY glEvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
GLAPI void APIENTRY glEvalPoint1 (GLint i);
GLAPI void APIENTRY glEvalPoint2 (GLint i, GLint j);
GLAPI void APIENTRY glFeedbackBuffer (GLsizei size, GLenum type, GLfloat *buffer);
GLAPI void APIENTRY glFinish (void);
GLAPI void APIENTRY glFlush (void);
GLAPI void APIENTRY glFogf (GLenum pname, GLfloat param);
GLAPI void APIENTRY glFogfv (GLenum pname, const GLfloat *params);
GLAPI void APIENTRY glFogi (GLenum pname, GLint param);
GLAPI void APIENTRY glFogiv (GLenum pname, const GLint *params);
GLAPI void APIENTRY glFrontFace (GLenum mode);
GLAPI void APIENTRY glFrustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLAPI GLuint APIENTRY glGenLists (GLsizei range);
GLAPI void APIENTRY glGenTextures (GLsizei n, GLuint *textures);
GLAPI void APIENTRY glGetBooleanv (GLenum pname, GLboolean *params);
GLAPI void APIENTRY glGetClipPlane (GLenum plane, GLdouble *equation);
GLAPI void APIENTRY glGetDoublev (GLenum pname, GLdouble *params);
GLAPI GLenum APIENTRY glGetError (void);
GLAPI void APIENTRY glGetFloatv (GLenum pname, GLfloat *params);
GLAPI void APIENTRY glGetIntegerv (GLenum pname, GLint *params);
GLAPI void APIENTRY glGetLightfv (GLenum light, GLenum pname, GLfloat *params);
GLAPI void APIENTRY glGetLightiv (GLenum light, GLenum pname, GLint *params);
GLAPI void APIENTRY glGetMapdv (GLenum target, GLenum query, GLdouble *v);
GLAPI void APIENTRY glGetMapfv (GLenum target, GLenum query, GLfloat *v);
GLAPI void APIENTRY glGetMapiv (GLenum target, GLenum query, GLint *v);
GLAPI void APIENTRY glGetMaterialfv (GLenum face, GLenum pname, GLfloat *params);
GLAPI void APIENTRY glGetMaterialiv (GLenum face, GLenum pname, GLint *params);
GLAPI void APIENTRY glGetPixelMapfv (GLenum map, GLfloat *values);
GLAPI void APIENTRY glGetPixelMapuiv (GLenum map, GLuint *values);
GLAPI void APIENTRY glGetPixelMapusv (GLenum map, GLushort *values);
GLAPI void APIENTRY glGetPointerv (GLenum pname, void* *params);
GLAPI void APIENTRY glGetPolygonStipple (GLubyte *mask);
GLAPI const GLubyte * APIENTRY glGetString (GLenum name);
GLAPI void APIENTRY glGetTexEnvfv (GLenum target, GLenum pname, GLfloat *params);
GLAPI void APIENTRY glGetTexEnviv (GLenum target, GLenum pname, GLint *params);
GLAPI void APIENTRY glGetTexGendv (GLenum coord, GLenum pname, GLdouble *params);
GLAPI void APIENTRY glGetTexGenfv (GLenum coord, GLenum pname, GLfloat *params);
GLAPI void APIENTRY glGetTexGeniv (GLenum coord, GLenum pname, GLint *params);
GLAPI void APIENTRY glGetTexImage (GLenum target, GLint level, GLenum format, GLenum type, void *pixels);
GLAPI void APIENTRY glGetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params);
GLAPI void APIENTRY glGetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params);
GLAPI void APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params);
GLAPI void APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint *params);
GLAPI void APIENTRY glHint (GLenum target, GLenum mode);
GLAPI void APIENTRY glIndexMask (GLuint mask);
GLAPI void APIENTRY glIndexPointer (GLenum type, GLsizei stride, const void *pointer);
GLAPI void APIENTRY glIndexd (GLdouble c);
GLAPI void APIENTRY glIndexdv (const GLdouble *c);
GLAPI void APIENTRY glIndexf (GLfloat c);
GLAPI void APIENTRY glIndexfv (const GLfloat *c);
GLAPI void APIENTRY glIndexi (GLint c);
GLAPI void APIENTRY glIndexiv (const GLint *c);
GLAPI void APIENTRY glIndexs (GLshort c);
GLAPI void APIENTRY glIndexsv (const GLshort *c);
GLAPI void APIENTRY glIndexub (GLubyte c);
GLAPI void APIENTRY glIndexubv (const GLubyte *c);
GLAPI void APIENTRY glInitNames (void);
GLAPI void APIENTRY glInterleavedArrays (GLenum format, GLsizei stride, const void *pointer);
GLAPI GLboolean APIENTRY glIsEnabled (GLenum cap);
GLAPI GLboolean APIENTRY glIsList (GLuint list);
GLAPI GLboolean APIENTRY glIsTexture (GLuint texture);
GLAPI void APIENTRY glLightModelf (GLenum pname, GLfloat param);
GLAPI void APIENTRY glLightModelfv (GLenum pname, const GLfloat *params);
GLAPI void APIENTRY glLightModeli (GLenum pname, GLint param);
GLAPI void APIENTRY glLightModeliv (GLenum pname, const GLint *params);
GLAPI void APIENTRY glLightf (GLenum light, GLenum pname, GLfloat param);
GLAPI void APIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat *params);
GLAPI void APIENTRY glLighti (GLenum light, GLenum pname, GLint param);
GLAPI void APIENTRY glLightiv (GLenum light, GLenum pname, const GLint *params);
GLAPI void APIENTRY glLineStipple (GLint factor, GLushort pattern);
GLAPI void APIENTRY glLineWidth (GLfloat width);
GLAPI void APIENTRY glListBase (GLuint base);
GLAPI void APIENTRY glLoadIdentity (void);
GLAPI void APIENTRY glLoadMatrixd (const GLdouble *m);
GLAPI void APIENTRY glLoadMatrixf (const GLfloat *m);
GLAPI void APIENTRY glLoadName (GLuint name);
GLAPI void APIENTRY glLogicOp (GLenum opcode);
GLAPI void APIENTRY glMap1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
GLAPI void APIENTRY glMap1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
GLAPI void APIENTRY glMap2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
GLAPI void APIENTRY glMap2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
GLAPI void APIENTRY glMapGrid1d (GLint un, GLdouble u1, GLdouble u2);
GLAPI void APIENTRY glMapGrid1f (GLint un, GLfloat u1, GLfloat u2);
GLAPI void APIENTRY glMapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
GLAPI void APIENTRY glMapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
GLAPI void APIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param);
GLAPI void APIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat *params);
GLAPI void APIENTRY glMateriali (GLenum face, GLenum pname, GLint param);
GLAPI void APIENTRY glMaterialiv (GLenum face, GLenum pname, const GLint *params);
GLAPI void APIENTRY glMatrixMode (GLenum mode);
GLAPI void APIENTRY glMultMatrixd (const GLdouble *m);
GLAPI void APIENTRY glMultMatrixf (const GLfloat *m);
GLAPI void APIENTRY glNewList (GLuint list, GLenum mode);
GLAPI void APIENTRY glNormal3b (GLbyte nx, GLbyte ny, GLbyte nz);
GLAPI void APIENTRY glNormal3bv (const GLbyte *v);
GLAPI void APIENTRY glNormal3d (GLdouble nx, GLdouble ny, GLdouble nz);
GLAPI void APIENTRY glNormal3dv (const GLdouble *v);
GLAPI void APIENTRY glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz);
GLAPI void APIENTRY glNormal3fv (const GLfloat *v);
GLAPI void APIENTRY glNormal3i (GLint nx, GLint ny, GLint nz);
GLAPI void APIENTRY glNormal3iv (const GLint *v);
GLAPI void APIENTRY glNormal3s (GLshort nx, GLshort ny, GLshort nz);
GLAPI void APIENTRY glNormal3sv (const GLshort *v);
GLAPI void APIENTRY glNormalPointer (GLenum type, GLsizei stride, const void *pointer);
GLAPI void APIENTRY glOrtho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLAPI void APIENTRY glPassThrough (GLfloat token);
GLAPI void APIENTRY glPixelMapfv (GLenum map, GLsizei mapsize, const GLfloat *values);
GLAPI void APIENTRY glPixelMapuiv (GLenum map, GLsizei mapsize, const GLuint *values);
GLAPI void APIENTRY glPixelMapusv (GLenum map, GLsizei mapsize, const GLushort *values);
GLAPI void APIENTRY glPixelStoref (GLenum pname, GLfloat param);
GLAPI void APIENTRY glPixelStorei (GLenum pname, GLint param);
GLAPI void APIENTRY glPixelTransferf (GLenum pname, GLfloat param);
GLAPI void APIENTRY glPixelTransferi (GLenum pname, GLint param);
GLAPI void APIENTRY glPixelZoom (GLfloat xfactor, GLfloat yfactor);
GLAPI void APIENTRY glPointSize (GLfloat size);
GLAPI void APIENTRY glPolygonMode (GLenum face, GLenum mode);
GLAPI void APIENTRY glPolygonOffset (GLfloat factor, GLfloat units);
GLAPI void APIENTRY glPolygonStipple (const GLubyte *mask);
GLAPI void APIENTRY glPopAttrib (void);
GLAPI void APIENTRY glPopClientAttrib (void);
GLAPI void APIENTRY glPopMatrix (void);
GLAPI void APIENTRY glPopName (void);
GLAPI void APIENTRY glPrioritizeTextures (GLsizei n, const GLuint *textures, const GLclampf *priorities);
GLAPI void APIENTRY glPushAttrib (GLbitfield mask);
GLAPI void APIENTRY glPushClientAttrib (GLbitfield mask);
GLAPI void APIENTRY glPushMatrix (void);
GLAPI void APIENTRY glPushName (GLuint name);
GLAPI void APIENTRY glRasterPos2d (GLdouble x, GLdouble y);
GLAPI void APIENTRY glRasterPos2dv (const GLdouble *v);
GLAPI void APIENTRY glRasterPos2f (GLfloat x, GLfloat y);
GLAPI void APIENTRY glRasterPos2fv (const GLfloat *v);
GLAPI void APIENTRY glRasterPos2i (GLint x, GLint y);
GLAPI void APIENTRY glRasterPos2iv (const GLint *v);
GLAPI void APIENTRY glRasterPos2s (GLshort x, GLshort y);
GLAPI void APIENTRY glRasterPos2sv (const GLshort *v);
GLAPI void APIENTRY glRasterPos3d (GLdouble x, GLdouble y, GLdouble z);
GLAPI void APIENTRY glRasterPos3dv (const GLdouble *v);
GLAPI void APIENTRY glRasterPos3f (GLfloat x, GLfloat y, GLfloat z);
GLAPI void APIENTRY glRasterPos3fv (const GLfloat *v);
GLAPI void APIENTRY glRasterPos3i (GLint x, GLint y, GLint z);
GLAPI void APIENTRY glRasterPos3iv (const GLint *v);
GLAPI void APIENTRY glRasterPos3s (GLshort x, GLshort y, GLshort z);
GLAPI void APIENTRY glRasterPos3sv (const GLshort *v);
GLAPI void APIENTRY glRasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w);
GLAPI void APIENTRY glRasterPos4dv (const GLdouble *v);
GLAPI void APIENTRY glRasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w);
GLAPI void APIENTRY glRasterPos4fv (const GLfloat *v);
GLAPI void APIENTRY glRasterPos4i (GLint x, GLint y, GLint z, GLint w);
GLAPI void APIENTRY glRasterPos4iv (const GLint *v);
GLAPI void APIENTRY glRasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w);
GLAPI void APIENTRY glRasterPos4sv (const GLshort *v);
GLAPI void APIENTRY glReadBuffer (GLenum mode);
GLAPI void APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
GLAPI void APIENTRY glRectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
GLAPI void APIENTRY glRectdv (const GLdouble *v1, const GLdouble *v2);
GLAPI void APIENTRY glRectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
GLAPI void APIENTRY glRectfv (const GLfloat *v1, const GLfloat *v2);
GLAPI void APIENTRY glRecti (GLint x1, GLint y1, GLint x2, GLint y2);
GLAPI void APIENTRY glRectiv (const GLint *v1, const GLint *v2);
GLAPI void APIENTRY glRects (GLshort x1, GLshort y1, GLshort x2, GLshort y2);
GLAPI void APIENTRY glRectsv (const GLshort *v1, const GLshort *v2);
GLAPI GLint APIENTRY glRenderMode (GLenum mode);
GLAPI void APIENTRY glRotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
GLAPI void APIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
GLAPI void APIENTRY glScaled (GLdouble x, GLdouble y, GLdouble z);
GLAPI void APIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z);
GLAPI void APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height);
GLAPI void APIENTRY glSelectBuffer (GLsizei size, GLuint *buffer);
GLAPI void APIENTRY glShadeModel (GLenum mode);
GLAPI void APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask);
GLAPI void APIENTRY glStencilMask (GLuint mask);
GLAPI void APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass);
GLAPI void APIENTRY glTexCoord1d (GLdouble s);
GLAPI void APIENTRY glTexCoord1dv (const GLdouble *v);
GLAPI void APIENTRY glTexCoord1f (GLfloat s);
GLAPI void APIENTRY glTexCoord1fv (const GLfloat *v);
GLAPI void APIENTRY glTexCoord1i (GLint s);
GLAPI void APIENTRY glTexCoord1iv (const GLint *v);
GLAPI void APIENTRY glTexCoord1s (GLshort s);
GLAPI void APIENTRY glTexCoord1sv (const GLshort *v);
GLAPI void APIENTRY glTexCoord2d (GLdouble s, GLdouble t);
GLAPI void APIENTRY glTexCoord2dv (const GLdouble *v);
GLAPI void APIENTRY glTexCoord2f (GLfloat s, GLfloat t);
GLAPI void APIENTRY glTexCoord2fv (const GLfloat *v);
GLAPI void APIENTRY glTexCoord2i (GLint s, GLint t);
GLAPI void APIENTRY glTexCoord2iv (const GLint *v);
GLAPI void APIENTRY glTexCoord2s (GLshort s, GLshort t);
GLAPI void APIENTRY glTexCoord2sv (const GLshort *v);
GLAPI void APIENTRY glTexCoord3d (GLdouble s, GLdouble t, GLdouble r);
GLAPI void APIENTRY glTexCoord3dv (const GLdouble *v);
GLAPI void APIENTRY glTexCoord3f (GLfloat s, GLfloat t, GLfloat r);
GLAPI void APIENTRY glTexCoord3fv (const GLfloat *v);
GLAPI void APIENTRY glTexCoord3i (GLint s, GLint t, GLint r);
GLAPI void APIENTRY glTexCoord3iv (const GLint *v);
GLAPI void APIENTRY glTexCoord3s (GLshort s, GLshort t, GLshort r);
GLAPI void APIENTRY glTexCoord3sv (const GLshort *v);
GLAPI void APIENTRY glTexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q);
GLAPI void APIENTRY glTexCoord4dv (const GLdouble *v);
GLAPI void APIENTRY glTexCoord4f (GLfloat s, GLfloat t, GLfloat r, GLfloat q);
GLAPI void APIENTRY glTexCoord4fv (const GLfloat *v);
GLAPI void APIENTRY glTexCoord4i (GLint s, GLint t, GLint r, GLint q);
GLAPI void APIENTRY glTexCoord4iv (const GLint *v);
GLAPI void APIENTRY glTexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q);
GLAPI void APIENTRY glTexCoord4sv (const GLshort *v);
GLAPI void APIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const void *pointer);
GLAPI void APIENTRY glTexEnvf (GLenum target, GLenum pname, GLfloat param);
GLAPI void APIENTRY glTexEnvfv (GLenum target, GLenum pname, const GLfloat *params);
GLAPI void APIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param);
GLAPI void APIENTRY glTexEnviv (GLenum target, GLenum pname, const GLint *params);
GLAPI void APIENTRY glTexGend (GLenum coord, GLenum pname, GLdouble param);
GLAPI void APIENTRY glTexGendv (GLenum coord, GLenum pname, const GLdouble *params);
GLAPI void APIENTRY glTexGenf (GLenum coord, GLenum pname, GLfloat param);
GLAPI void APIENTRY glTexGenfv (GLenum coord, GLenum pname, const GLfloat *params);
GLAPI void APIENTRY glTexGeni (GLenum coord, GLenum pname, GLint param);
GLAPI void APIENTRY glTexGeniv (GLenum coord, GLenum pname, const GLint *params);
GLAPI void APIENTRY glTexImage1D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels);
GLAPI void APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
GLAPI void APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param);
GLAPI void APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params);
GLAPI void APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param);
GLAPI void APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint *params);
GLAPI void APIENTRY glTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
GLAPI void APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
GLAPI void APIENTRY glTranslated (GLdouble x, GLdouble y, GLdouble z);
GLAPI void APIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z);
GLAPI void APIENTRY glVertex2d (GLdouble x, GLdouble y);
GLAPI void APIENTRY glVertex2dv (const GLdouble *v);
GLAPI void APIENTRY glVertex2f (GLfloat x, GLfloat y);
GLAPI void APIENTRY glVertex2fv (const GLfloat *v);
GLAPI void APIENTRY glVertex2i (GLint x, GLint y);
GLAPI void APIENTRY glVertex2iv (const GLint *v);
GLAPI void APIENTRY glVertex2s (GLshort x, GLshort y);
GLAPI void APIENTRY glVertex2sv (const GLshort *v);
GLAPI void APIENTRY glVertex3d (GLdouble x, GLdouble y, GLdouble z);
GLAPI void APIENTRY glVertex3dv (const GLdouble *v);
GLAPI void APIENTRY glVertex3f (GLfloat x, GLfloat y, GLfloat z);
GLAPI void APIENTRY glVertex3fv (const GLfloat *v);
GLAPI void APIENTRY glVertex3i (GLint x, GLint y, GLint z);
GLAPI void APIENTRY glVertex3iv (const GLint *v);
GLAPI void APIENTRY glVertex3s (GLshort x, GLshort y, GLshort z);
GLAPI void APIENTRY glVertex3sv (const GLshort *v);
GLAPI void APIENTRY glVertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w);
GLAPI void APIENTRY glVertex4dv (const GLdouble *v);
GLAPI void APIENTRY glVertex4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w);
GLAPI void APIENTRY glVertex4fv (const GLfloat *v);
GLAPI void APIENTRY glVertex4i (GLint x, GLint y, GLint z, GLint w);
GLAPI void APIENTRY glVertex4iv (const GLint *v);
GLAPI void APIENTRY glVertex4s (GLshort x, GLshort y, GLshort z, GLshort w);
GLAPI void APIENTRY glVertex4sv (const GLshort *v);
GLAPI void APIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const void *pointer);
GLAPI void APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height);
}
} // axl.glw.gl
} // axl.glw
} // axl