#pragma once
#include <stdint.h>
#include "lib.hpp"
#include "gl.hpp"

namespace axl {
namespace glw {
namespace glext {
using namespace axl::glw::gl;

// GL_ARB_arrays_of_arrays
AXLGLWAPI bool GL_ARB_arrays_of_arrays;

// GL_ARB_base_instance
typedef void (APIENTRY * PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC) (GLenum mode, GLint first, GLsizei count, GLsizei primcount, GLuint baseinstance);
typedef void (APIENTRY * PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC) (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei primcount, GLuint baseinstance);
typedef void (APIENTRY * PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC) (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei primcount, GLint basevertex, GLuint baseinstance);
AXLGLWAPI PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC glDrawArraysInstancedBaseInstance;
AXLGLWAPI PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC glDrawElementsInstancedBaseInstance;
AXLGLWAPI PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC glDrawElementsInstancedBaseVertexBaseInstance;
AXLGLWAPI bool GL_ARB_base_instance;

// GL_ARB_blend_func_extended
AXLGLWCONSTMODIFIER GLenum GL_SRC1_COLOR = 0x88F9;
AXLGLWCONSTMODIFIER GLenum GL_ONE_MINUS_SRC1_COLOR = 0x88FA;
AXLGLWCONSTMODIFIER GLenum GL_ONE_MINUS_SRC1_ALPHA = 0x88FB;
AXLGLWCONSTMODIFIER GLenum GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = 0x88FC;
typedef void (APIENTRY * PFNGLBINDFRAGDATALOCATIONINDEXEDPROC) (GLuint program, GLuint colorNumber, GLuint index, const GLubyte * name);
typedef GLint (APIENTRY * PFNGLGETFRAGDATAINDEXPROC) (GLuint program, const GLubyte * name);
AXLGLWAPI PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed;
AXLGLWAPI PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex;
AXLGLWAPI bool GL_ARB_blend_func_extended;

// GL_ARB_buffer_storage
AXLGLWCONSTMODIFIER GLenum GL_MAP_READ_BIT = 0x0001;
AXLGLWCONSTMODIFIER GLenum GL_MAP_WRITE_BIT = 0x0002;
AXLGLWCONSTMODIFIER GLenum GL_MAP_PERSISTENT_BIT = 0x00000040;
AXLGLWCONSTMODIFIER GLenum GL_MAP_COHERENT_BIT = 0x00000080;
AXLGLWCONSTMODIFIER GLenum GL_DYNAMIC_STORAGE_BIT = 0x0100;
AXLGLWCONSTMODIFIER GLenum GL_CLIENT_STORAGE_BIT = 0x0200;
AXLGLWCONSTMODIFIER GLenum GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT = 0x00004000;
AXLGLWCONSTMODIFIER GLenum GL_BUFFER_IMMUTABLE_STORAGE = 0x821F;
AXLGLWCONSTMODIFIER GLenum GL_BUFFER_STORAGE_FLAGS = 0x8220;
typedef void (APIENTRY * PFNGLBUFFERSTORAGEPROC) (GLenum target, GLsizeiptr size, const void *data, GLbitfield flags);
AXLGLWAPI PFNGLBUFFERSTORAGEPROC glBufferStorage;
AXLGLWAPI bool GL_ARB_buffer_storage;

// GL_ARB_clear_buffer_object
typedef void (APIENTRY * PFNGLCLEARBUFFERDATAPROC) (GLenum target, GLenum internalformat, GLenum format, GLenum type, const void *data);
typedef void (APIENTRY * PFNGLCLEARBUFFERSUBDATAPROC) (GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
typedef void (APIENTRY * PFNGLCLEARNAMEDBUFFERDATAEXTPROC) (GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const void *data);
typedef void (APIENTRY * PFNGLCLEARNAMEDBUFFERSUBDATAEXTPROC) (GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
AXLGLWAPI PFNGLCLEARBUFFERDATAPROC glClearBufferData;
AXLGLWAPI PFNGLCLEARBUFFERSUBDATAPROC glClearBufferSubData;
AXLGLWAPI PFNGLCLEARNAMEDBUFFERDATAEXTPROC glClearNamedBufferDataEXT;
AXLGLWAPI PFNGLCLEARNAMEDBUFFERSUBDATAEXTPROC glClearNamedBufferSubDataEXT;
AXLGLWAPI bool GL_ARB_clear_buffer_object;

// GL_ARB_ES2_compatibility
AXLGLWCONSTMODIFIER GLenum GL_FIXED = 0x140C;
AXLGLWCONSTMODIFIER GLenum GL_IMPLEMENTATION_COLOR_READ_TYPE = 0x8B9A;
AXLGLWCONSTMODIFIER GLenum GL_IMPLEMENTATION_COLOR_READ_FORMAT = 0x8B9B;
AXLGLWCONSTMODIFIER GLenum GL_RGB565 = 0x8D62;
AXLGLWCONSTMODIFIER GLenum GL_LOW_FLOAT = 0x8DF0;
AXLGLWCONSTMODIFIER GLenum GL_MEDIUM_FLOAT = 0x8DF1;
AXLGLWCONSTMODIFIER GLenum GL_HIGH_FLOAT = 0x8DF2;
AXLGLWCONSTMODIFIER GLenum GL_LOW_INT = 0x8DF3;
AXLGLWCONSTMODIFIER GLenum GL_MEDIUM_INT = 0x8DF4;
AXLGLWCONSTMODIFIER GLenum GL_HIGH_INT = 0x8DF5;
AXLGLWCONSTMODIFIER GLenum GL_SHADER_BINARY_FORMATS = 0x8DF8;
AXLGLWCONSTMODIFIER GLenum GL_NUM_SHADER_BINARY_FORMATS = 0x8DF9;
AXLGLWCONSTMODIFIER GLenum GL_SHADER_COMPILER = 0x8DFA;
AXLGLWCONSTMODIFIER GLenum GL_MAX_VERTEX_UNIFORM_VECTORS = 0x8DFB;
AXLGLWCONSTMODIFIER GLenum GL_MAX_VARYING_VECTORS = 0x8DFC;
AXLGLWCONSTMODIFIER GLenum GL_MAX_FRAGMENT_UNIFORM_VECTORS = 0x8DFD;
typedef int GLfixed;
typedef void (APIENTRY * PFNGLCLEARDEPTHFPROC) (GLclampf d);
typedef void (APIENTRY * PFNGLDEPTHRANGEFPROC) (GLclampf n, GLclampf f);
typedef void (APIENTRY * PFNGLGETSHADERPRECISIONFORMATPROC) (GLenum shadertype, GLenum precisiontype, GLint* range, GLint *precision);
typedef void (APIENTRY * PFNGLRELEASESHADERCOMPILERPROC) (void);
typedef void (APIENTRY * PFNGLSHADERBINARYPROC) (GLsizei count, const GLuint* shaders, GLenum binaryformat, const void*binary, GLsizei length);
AXLGLWAPI PFNGLCLEARDEPTHFPROC glClearDepthf;
AXLGLWAPI PFNGLDEPTHRANGEFPROC glDepthRangef;
AXLGLWAPI PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
AXLGLWAPI PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler;
AXLGLWAPI PFNGLSHADERBINARYPROC glShaderBinary;
AXLGLWAPI bool GL_ARB_ES2_compatibility;

// GL_ARB_ES3_compatibility
AXLGLWCONSTMODIFIER GLenum GL_TEXTURE_IMMUTABLE_LEVELS = 0x82DF;
AXLGLWCONSTMODIFIER GLenum GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69;
AXLGLWCONSTMODIFIER GLenum GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A;
AXLGLWCONSTMODIFIER GLenum GL_MAX_ELEMENT_INDEX = 0x8D6B;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_R11_EAC = 0x9270;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_SIGNED_R11_EAC = 0x9271;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_RG11_EAC = 0x9272;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_SIGNED_RG11_EAC = 0x9273;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_RGB8_ETC2 = 0x9274;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_SRGB8_ETC2 = 0x9275;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9276;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9277;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_RGBA8_ETC2_EAC = 0x9278;
AXLGLWCONSTMODIFIER GLenum GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x9279;
AXLGLWAPI bool GL_ARB_ES3_compatibility;

// GL_ARB_ES3_1_compatibility
typedef void (APIENTRY * PFNGLMEMORYBARRIERBYREGIONPROC) (GLbitfield barriers);
AXLGLWAPI PFNGLMEMORYBARRIERBYREGIONPROC glMemoryBarrierByRegion;
AXLGLWAPI bool GL_ARB_ES3_1_compatibility;

// GL_ARB_ES3_2_compatibility
AXLGLWCONSTMODIFIER GLenum GL_PRIMITIVE_BOUNDING_BOX_ARB = 0x92BE;
AXLGLWCONSTMODIFIER GLenum GL_MULTISAMPLE_LINE_WIDTH_RANGE_ARB = 0x9381;
AXLGLWCONSTMODIFIER GLenum GL_MULTISAMPLE_LINE_WIDTH_GRANULARITY_ARB = 0x9382;
typedef void (APIENTRY * PFNGLPRIMITIVEBOUNDINGBOXARBPROC) (GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW);
AXLGLWAPI PFNGLPRIMITIVEBOUNDINGBOXARBPROC glPrimitiveBoundingBoxARB;
AXLGLWAPI bool GL_ARB_ES3_2_compatibility;

// GL_ARB_imaging
AXLGLWCONSTMODIFIER GLenum GL_CONSTANT_COLOR = 0x8001;
AXLGLWCONSTMODIFIER GLenum GL_ONE_MINUS_CONSTANT_COLOR = 0x8002;
AXLGLWCONSTMODIFIER GLenum GL_CONSTANT_ALPHA = 0x8003;
AXLGLWCONSTMODIFIER GLenum GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004;
AXLGLWCONSTMODIFIER GLenum GL_BLEND_COLOR = 0x8005;
AXLGLWCONSTMODIFIER GLenum GL_FUNC_ADD = 0x8006;
AXLGLWCONSTMODIFIER GLenum GL_MIN = 0x8007;
AXLGLWCONSTMODIFIER GLenum GL_MAX = 0x8008;
AXLGLWCONSTMODIFIER GLenum GL_BLEND_EQUATION = 0x8009;
AXLGLWCONSTMODIFIER GLenum GL_FUNC_SUBTRACT = 0x800A;
AXLGLWCONSTMODIFIER GLenum GL_FUNC_REVERSE_SUBTRACT = 0x800B;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_1D = 0x8010;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_2D = 0x8011;
AXLGLWCONSTMODIFIER GLenum GL_SEPARABLE_2D = 0x8012;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_BORDER_MODE = 0x8013;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_FILTER_SCALE = 0x8014;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_FILTER_BIAS = 0x8015;
AXLGLWCONSTMODIFIER GLenum GL_REDUCE = 0x8016;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_FORMAT = 0x8017;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_WIDTH = 0x8018;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_HEIGHT = 0x8019;
AXLGLWCONSTMODIFIER GLenum GL_MAX_CONVOLUTION_WIDTH = 0x801A;
AXLGLWCONSTMODIFIER GLenum GL_MAX_CONVOLUTION_HEIGHT = 0x801B;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_RED_SCALE = 0x801C;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_GREEN_SCALE = 0x801D;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_BLUE_SCALE = 0x801E;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_ALPHA_SCALE = 0x801F;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_RED_BIAS = 0x8020;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_GREEN_BIAS = 0x8021;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_BLUE_BIAS = 0x8022;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_ALPHA_BIAS = 0x8023;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM = 0x8024;
AXLGLWCONSTMODIFIER GLenum GL_PROXY_HISTOGRAM = 0x8025;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_WIDTH = 0x8026;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_FORMAT = 0x8027;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_RED_SIZE = 0x8028;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_GREEN_SIZE = 0x8029;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_BLUE_SIZE = 0x802A;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_ALPHA_SIZE = 0x802B;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_LUMINANCE_SIZE = 0x802C;
AXLGLWCONSTMODIFIER GLenum GL_HISTOGRAM_SINK = 0x802D;
AXLGLWCONSTMODIFIER GLenum GL_MINMAX = 0x802E;
AXLGLWCONSTMODIFIER GLenum GL_MINMAX_FORMAT = 0x802F;
AXLGLWCONSTMODIFIER GLenum GL_MINMAX_SINK = 0x8030;
AXLGLWCONSTMODIFIER GLenum GL_TABLE_TOO_LARGE = 0x8031;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_MATRIX = 0x80B1;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_MATRIX_STACK_DEPTH = 0x80B2;
AXLGLWCONSTMODIFIER GLenum GL_MAX_COLOR_MATRIX_STACK_DEPTH = 0x80B3;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_RED_SCALE = 0x80B4;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_GREEN_SCALE = 0x80B5;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_BLUE_SCALE = 0x80B6;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_ALPHA_SCALE = 0x80B7;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_RED_BIAS = 0x80B8;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_GREEN_BIAS = 0x80B9;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_BLUE_BIAS = 0x80BA;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_ALPHA_BIAS = 0x80BB;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE = 0x80D0;
AXLGLWCONSTMODIFIER GLenum GL_POST_CONVOLUTION_COLOR_TABLE = 0x80D1;
AXLGLWCONSTMODIFIER GLenum GL_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D2;
AXLGLWCONSTMODIFIER GLenum GL_PROXY_COLOR_TABLE = 0x80D3;
AXLGLWCONSTMODIFIER GLenum GL_PROXY_POST_CONVOLUTION_COLOR_TABLE = 0x80D4;
AXLGLWCONSTMODIFIER GLenum GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D5;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_SCALE = 0x80D6;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_BIAS = 0x80D7;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_FORMAT = 0x80D8;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_WIDTH = 0x80D9;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_RED_SIZE = 0x80DA;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_GREEN_SIZE = 0x80DB;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_BLUE_SIZE = 0x80DC;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_ALPHA_SIZE = 0x80DD;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_LUMINANCE_SIZE = 0x80DE;
AXLGLWCONSTMODIFIER GLenum GL_COLOR_TABLE_INTENSITY_SIZE = 0x80DF;
AXLGLWCONSTMODIFIER GLenum GL_IGNORE_BORDER = 0x8150;
AXLGLWCONSTMODIFIER GLenum GL_CONSTANT_BORDER = 0x8151;
AXLGLWCONSTMODIFIER GLenum GL_WRAP_BORDER = 0x8152;
AXLGLWCONSTMODIFIER GLenum GL_REPLICATE_BORDER = 0x8153;
AXLGLWCONSTMODIFIER GLenum GL_CONVOLUTION_BORDER_COLOR = 0x8154;

typedef void (APIENTRY * PFNGLCOLORSUBTABLEPROC) (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const void *data);
typedef void (APIENTRY * PFNGLCOLORTABLEPROC) (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const void *table);
typedef void (APIENTRY * PFNGLCOLORTABLEPARAMETERFVPROC) (GLenum target, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLCOLORTABLEPARAMETERIVPROC) (GLenum target, GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLCONVOLUTIONFILTER1DPROC) (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const void *image);
typedef void (APIENTRY * PFNGLCONVOLUTIONFILTER2DPROC) (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *image);
typedef void (APIENTRY * PFNGLCONVOLUTIONPARAMETERFPROC) (GLenum target, GLenum pname, GLfloat params);
typedef void (APIENTRY * PFNGLCONVOLUTIONPARAMETERFVPROC) (GLenum target, GLenum pname, const GLfloat *params);
typedef void (APIENTRY * PFNGLCONVOLUTIONPARAMETERIPROC) (GLenum target, GLenum pname, GLint params);
typedef void (APIENTRY * PFNGLCONVOLUTIONPARAMETERIVPROC) (GLenum target, GLenum pname, const GLint *params);
typedef void (APIENTRY * PFNGLCOPYCOLORSUBTABLEPROC) (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width);
typedef void (APIENTRY * PFNGLCOPYCOLORTABLEPROC) (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
typedef void (APIENTRY * PFNGLCOPYCONVOLUTIONFILTER1DPROC) (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
typedef void (APIENTRY * PFNGLCOPYCONVOLUTIONFILTER2DPROC) (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
typedef void (APIENTRY * PFNGLGETCOLORTABLEPROC) (GLenum target, GLenum format, GLenum type, void *table);
typedef void (APIENTRY * PFNGLGETCOLORTABLEPARAMETERFVPROC) (GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETCOLORTABLEPARAMETERIVPROC) (GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETCONVOLUTIONFILTERPROC) (GLenum target, GLenum format, GLenum type, void *image);
typedef void (APIENTRY * PFNGLGETCONVOLUTIONPARAMETERFVPROC) (GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETCONVOLUTIONPARAMETERIVPROC) (GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETHISTOGRAMPROC) (GLenum target, GLboolean reset, GLenum format, GLenum type, void *values);
typedef void (APIENTRY * PFNGLGETHISTOGRAMPARAMETERFVPROC) (GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETHISTOGRAMPARAMETERIVPROC) (GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETMINMAXPROC) (GLenum target, GLboolean reset, GLenum format, GLenum types, void *values);
typedef void (APIENTRY * PFNGLGETMINMAXPARAMETERFVPROC) (GLenum target, GLenum pname, GLfloat *params);
typedef void (APIENTRY * PFNGLGETMINMAXPARAMETERIVPROC) (GLenum target, GLenum pname, GLint *params);
typedef void (APIENTRY * PFNGLGETSEPARABLEFILTERPROC) (GLenum target, GLenum format, GLenum type, void *row, void *column, void *span);
typedef void (APIENTRY * PFNGLHISTOGRAMPROC) (GLenum target, GLsizei width, GLenum internalformat, GLboolean sink);
typedef void (APIENTRY * PFNGLMINMAXPROC) (GLenum target, GLenum internalformat, GLboolean sink);
typedef void (APIENTRY * PFNGLRESETHISTOGRAMPROC) (GLenum target);
typedef void (APIENTRY * PFNGLRESETMINMAXPROC) (GLenum target);
typedef void (APIENTRY * PFNGLSEPARABLEFILTER2DPROC) (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *row, const void *column);

AXLGLWAPI PFNGLCOLORSUBTABLEPROC glColorSubTable;
AXLGLWAPI PFNGLCOLORTABLEPROC glColorTable;
AXLGLWAPI PFNGLCOLORTABLEPARAMETERFVPROC glColorTableParameterfv;
AXLGLWAPI PFNGLCOLORTABLEPARAMETERIVPROC glColorTableParameteriv;
AXLGLWAPI PFNGLCONVOLUTIONFILTER1DPROC glConvolutionFilter1D;
AXLGLWAPI PFNGLCONVOLUTIONFILTER2DPROC glConvolutionFilter2D;
AXLGLWAPI PFNGLCONVOLUTIONPARAMETERFPROC glConvolutionParameterf;
AXLGLWAPI PFNGLCONVOLUTIONPARAMETERFVPROC glConvolutionParameterfv;
AXLGLWAPI PFNGLCONVOLUTIONPARAMETERIPROC glConvolutionParameteri;
AXLGLWAPI PFNGLCONVOLUTIONPARAMETERIVPROC glConvolutionParameteriv;
AXLGLWAPI PFNGLCOPYCOLORSUBTABLEPROC glCopyColorSubTable;
AXLGLWAPI PFNGLCOPYCOLORTABLEPROC glCopyColorTable;
AXLGLWAPI PFNGLCOPYCONVOLUTIONFILTER1DPROC glCopyConvolutionFilter1D;
AXLGLWAPI PFNGLCOPYCONVOLUTIONFILTER2DPROC glCopyConvolutionFilter2D;
AXLGLWAPI PFNGLGETCOLORTABLEPROC glGetColorTable;
AXLGLWAPI PFNGLGETCOLORTABLEPARAMETERFVPROC glGetColorTableParameterfv;
AXLGLWAPI PFNGLGETCOLORTABLEPARAMETERIVPROC glGetColorTableParameteriv;
AXLGLWAPI PFNGLGETCONVOLUTIONFILTERPROC glGetConvolutionFilter;
AXLGLWAPI PFNGLGETCONVOLUTIONPARAMETERFVPROC glGetConvolutionParameterfv;
AXLGLWAPI PFNGLGETCONVOLUTIONPARAMETERIVPROC glGetConvolutionParameteriv;
AXLGLWAPI PFNGLGETHISTOGRAMPROC glGetHistogram;
AXLGLWAPI PFNGLGETHISTOGRAMPARAMETERFVPROC glGetHistogramParameterfv;
AXLGLWAPI PFNGLGETHISTOGRAMPARAMETERIVPROC glGetHistogramParameteriv;
AXLGLWAPI PFNGLGETMINMAXPROC glGetMinmax;
AXLGLWAPI PFNGLGETMINMAXPARAMETERFVPROC glGetMinmaxParameterfv;
AXLGLWAPI PFNGLGETMINMAXPARAMETERIVPROC glGetMinmaxParameteriv;
AXLGLWAPI PFNGLGETSEPARABLEFILTERPROC glGetSeparableFilter;
AXLGLWAPI PFNGLHISTOGRAMPROC glHistogram;
AXLGLWAPI PFNGLMINMAXPROC glMinmax;
AXLGLWAPI PFNGLRESETHISTOGRAMPROC glResetHistogram;
AXLGLWAPI PFNGLRESETMINMAXPROC glResetMinmax;
AXLGLWAPI PFNGLSEPARABLEFILTER2DPROC glSeparableFilter2D;
AXLGLWAPI bool GL_ARB_imaging;

// GL_ARB_shadow
AXLGLWCONSTMODIFIER GLenum GL_TEXTURE_COMPARE_MODE_ARB = 0x884C;
AXLGLWCONSTMODIFIER GLenum GL_TEXTURE_COMPARE_FUNC_ARB = 0x884D;
AXLGLWCONSTMODIFIER GLenum GL_COMPARE_R_TO_TEXTURE_ARB = 0x884E;
AXLGLWAPI bool GL_ARB_shadow;

// GL_ARB_sync
AXLGLWCONSTMODIFIER GLenum GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001;
AXLGLWCONSTMODIFIER GLenum GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111;
AXLGLWCONSTMODIFIER GLenum GL_OBJECT_TYPE = 0x9112;
AXLGLWCONSTMODIFIER GLenum GL_SYNC_CONDITION = 0x9113;
AXLGLWCONSTMODIFIER GLenum GL_SYNC_STATUS = 0x9114;
AXLGLWCONSTMODIFIER GLenum GL_SYNC_FLAGS = 0x9115;
AXLGLWCONSTMODIFIER GLenum GL_SYNC_FENCE = 0x9116;
AXLGLWCONSTMODIFIER GLenum GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117;
AXLGLWCONSTMODIFIER GLenum GL_UNSIGNALED = 0x9118;
AXLGLWCONSTMODIFIER GLenum GL_SIGNALED = 0x9119;
AXLGLWCONSTMODIFIER GLenum GL_ALREADY_SIGNALED = 0x911A;
AXLGLWCONSTMODIFIER GLenum GL_TIMEOUT_EXPIRED = 0x911B;
AXLGLWCONSTMODIFIER GLenum GL_CONDITION_SATISFIED = 0x911C;
AXLGLWCONSTMODIFIER GLenum GL_WAIT_FAILED = 0x911D;
AXLGLWCONSTMODIFIER unsigned long long GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFFull;
typedef GLenum (APIENTRY * PFNGLCLIENTWAITSYNCPROC) (GLsync gl_sync,GLbitfield flags,GLuint64 timeout);
typedef void (APIENTRY * PFNGLDELETESYNCPROC) (GLsync gl_sync);
typedef GLsync (APIENTRY * PFNGLFENCESYNCPROC) (GLenum condition,GLbitfield flags);
typedef void (APIENTRY * PFNGLGETINTEGER64VPROC) (GLenum pname, GLint64* params);
typedef void (APIENTRY * PFNGLGETSYNCIVPROC) (GLsync gl_sync,GLenum pname,GLsizei bufSize,GLsizei* length, GLint *values);
typedef GLboolean (APIENTRY * PFNGLISSYNCPROC) (GLsync gl_sync);
typedef void (APIENTRY * PFNGLWAITSYNCPROC) (GLsync gl_sync,GLbitfield flags,GLuint64 timeout);
AXLGLWAPI PFNGLCLIENTWAITSYNCPROC glClientWaitSync;
AXLGLWAPI PFNGLDELETESYNCPROC glDeleteSync;
AXLGLWAPI PFNGLFENCESYNCPROC glFenceSync;
AXLGLWAPI PFNGLGETINTEGER64VPROC glGetInteger64v;
AXLGLWAPI PFNGLGETSYNCIVPROC glGetSynciv;
AXLGLWAPI PFNGLISSYNCPROC glIsSync;
AXLGLWAPI PFNGLWAITSYNCPROC glWaitSync;
AXLGLWAPI bool GL_ARB_sync;

// GL_ARB_tessellation_shader
AXLGLWCONSTMODIFIER GLenum GL_PATCHES = 0xE;
AXLGLWCONSTMODIFIER GLenum GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER = 0x84F0;
AXLGLWCONSTMODIFIER GLenum GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x84F1;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x886C;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x886D;
AXLGLWCONSTMODIFIER GLenum GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E1E;
AXLGLWCONSTMODIFIER GLenum GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E1F;
AXLGLWCONSTMODIFIER GLenum GL_PATCH_VERTICES = 0x8E72;
AXLGLWCONSTMODIFIER GLenum GL_PATCH_DEFAULT_INNER_LEVEL = 0x8E73;
AXLGLWCONSTMODIFIER GLenum GL_PATCH_DEFAULT_OUTER_LEVEL = 0x8E74;
AXLGLWCONSTMODIFIER GLenum GL_TESS_CONTROL_OUTPUT_VERTICES = 0x8E75;
AXLGLWCONSTMODIFIER GLenum GL_TESS_GEN_MODE = 0x8E76;
AXLGLWCONSTMODIFIER GLenum GL_TESS_GEN_SPACING = 0x8E77;
AXLGLWCONSTMODIFIER GLenum GL_TESS_GEN_VERTEX_ORDER = 0x8E78;
AXLGLWCONSTMODIFIER GLenum GL_TESS_GEN_POINT_MODE = 0x8E79;
AXLGLWCONSTMODIFIER GLenum GL_ISOLINES = 0x8E7A;
AXLGLWCONSTMODIFIER GLenum GL_FRACTIONAL_ODD = 0x8E7B;
AXLGLWCONSTMODIFIER GLenum GL_FRACTIONAL_EVEN = 0x8E7C;
AXLGLWCONSTMODIFIER GLenum GL_MAX_PATCH_VERTICES = 0x8E7D;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_GEN_LEVEL = 0x8E7E;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E7F;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E80;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x8E81;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x8E82;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x8E83;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_PATCH_COMPONENTS = 0x8E84;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x8E85;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x8E86;
AXLGLWCONSTMODIFIER GLenum GL_TESS_EVALUATION_SHADER = 0x8E87;
AXLGLWCONSTMODIFIER GLenum GL_TESS_CONTROL_SHADER = 0x8E88;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x8E89;
AXLGLWCONSTMODIFIER GLenum GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x8E8A;
typedef void (APIENTRY * PFNGLPATCHPARAMETERFVPROC) (GLenum pname, const GLfloat* values);
typedef void (APIENTRY * PFNGLPATCHPARAMETERIPROC) (GLenum pname, GLint value);
AXLGLWAPI PFNGLPATCHPARAMETERFVPROC glPatchParameterfv;
AXLGLWAPI PFNGLPATCHPARAMETERIPROC glPatchParameteri;
AXLGLWAPI bool GL_ARB_tessellation_shader;

} // namespace axl.glw.glext
} // namespace axl.glw
} // namespace axl
